const film=document.querySelector('.hero-film');
let hlsPlayer,filmVisible=false;
const filmSource='https://stream.mux.com/Aa02T7oM1wH5Mk5EEVDYhbZ1ChcdhRsS2m1NYyx4Ua1g.m3u8';
function playFilm(){if(!filmVisible||paused||reduced.matches||document.hidden){film.pause();return}film.play().catch(()=>{})}
if(!reduced.matches){if(window.Hls&&Hls.isSupported()){hlsPlayer=new Hls({maxBufferLength:15,maxMaxBufferLength:30});hlsPlayer.loadSource(filmSource);hlsPlayer.attachMedia(film);hlsPlayer.on(Hls.Events.MANIFEST_PARSED,playFilm);hlsPlayer.on(Hls.Events.ERROR,(_,data)=>{if(data.fatal){hlsPlayer.destroy();film.removeAttribute('src')}})}else if(film.canPlayType('application/vnd.apple.mpegurl')){film.src=filmSource;film.addEventListener('loadedmetadata',playFilm,{once:true})}}
const filmObserver=new IntersectionObserver(entries=>{filmVisible=entries[0].isIntersecting;playFilm()});filmObserver.observe(film);
motion.addEventListener('click',()=>{document.body.classList.toggle('motion-paused',paused);playFilm()});reduced.addEventListener('change',playFilm);document.addEventListener('visibilitychange',playFilm);
const role=document.getElementById('changing-role'),roles=['Kết nối con người.','Phát triển nhân lực.','Đồng hành sức khỏe.'];let roleIndex=0;
const roleTimer=setInterval(()=>{if(paused||reduced.matches||document.hidden)return;roleIndex=(roleIndex+1)%roles.length;role.textContent=roles[roleIndex];role.animate([{opacity:0,transform:'translateY(8px)'},{opacity:1,transform:'translateY(0)'}],{duration:450,easing:'ease-out'})},3200);
// Gentle opposing gallery layers; no scroll capture or forced scrolling.
const parallaxPhotos=[...document.querySelectorAll('.photos img,.japan img')];let parallaxQueued=false;
function galleryDepth(){parallaxQueued=false;const disabled=paused||reduced.matches||innerWidth<701;parallaxPhotos.forEach((image,i)=>{if(disabled){image.style.transform='';return}const r=image.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)return;const offset=Math.max(-20,Math.min(20,(r.top+r.height/2-innerHeight/2)*.045));image.style.transform=`translateY(${offset*(i%2?1:-1)}px) scale(1.07)`})}
addEventListener('scroll',()=>{if(!parallaxQueued){parallaxQueued=true;requestAnimationFrame(galleryDepth)}},{passive:true});motion.addEventListener('click',galleryDepth);reduced.addEventListener('change',galleryDepth);
let hasIntro=false;try{hasIntro=sessionStorage.getItem('motion-intro')==='1';sessionStorage.setItem('motion-intro','1')}catch{}
if(!hasIntro&&!reduced.matches){const overlay=document.createElement('div');overlay.className='intro-screen';overlay.setAttribute('aria-hidden','true');overlay.innerHTML='<span class="intro-label">TƯỜNG HẢI / FOUNDER PROFILE</span><span class="intro-word">Kết nối.</span><span class="intro-count">000</span><span class="intro-track"></span>';document.body.append(overlay);const started=performance.now(),word=overlay.querySelector('.intro-word'),count=overlay.querySelector('.intro-count'),track=overlay.querySelector('.intro-track');let stage=-1;const words=['Kết nối.','Đồng hành.','Kiến tạo.'];function introTick(now){const progress=Math.min((now-started)/2100,1),next=Math.min(2,Math.floor(progress*3));count.textContent=String(Math.floor(progress*100)).padStart(3,'0');track.style.transform=`scaleX(${progress})`;if(next!==stage){stage=next;word.textContent=words[stage];word.animate([{opacity:0,transform:'translateY(15px)'},{opacity:1,transform:'translateY(0)'}],{duration:400,easing:'ease-out'})}if(progress<1)requestAnimationFrame(introTick);else{overlay.animate([{opacity:1,transform:'translateY(0)'},{opacity:0,transform:'translateY(-30px)'}],{duration:650,easing:'cubic-bezier(.16,1,.3,1)'}).finished.finally(()=>overlay.remove())}}requestAnimationFrame(introTick);setTimeout(()=>overlay.remove(),4000)}
