const menu=document.querySelector('.menu'),nav=document.querySelector('nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);menu.textContent=open?'Đóng ×':'Menu ＋'});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.textContent='Menu ＋'}));
const tabs=[...document.querySelectorAll('[role=tab]')];function select(tab){tabs.forEach(t=>{const active=t===tab;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;document.getElementById(t.getAttribute('aria-controls')).hidden=!active})}tabs.forEach((t,i)=>{t.addEventListener('click',()=>select(t));t.addEventListener('keydown',e=>{let j;if(e.key==='ArrowRight')j=(i+1)%tabs.length;if(e.key==='ArrowLeft')j=(i+tabs.length-1)%tabs.length;if(e.key==='Home')j=0;if(e.key==='End')j=tabs.length-1;if(j!==undefined){e.preventDefault();select(tabs[j]);tabs[j].focus()}})});
// Rotate 3D world-space rings, then project them with perspective onto the canvas.
const canvas=document.getElementById('orbit'),ctx=canvas.getContext('2d'),motion=document.querySelector('.motion'),reduced=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches,visible=true,angle=0,last=0,frame=0;function label(){motion.textContent=paused?'Bật chuyển động':'Tạm dừng chuyển động';motion.setAttribute('aria-pressed',String(paused))}label();function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0);start()}new ResizeObserver(resize).observe(canvas);function draw(time){frame=0;const w=canvas.clientWidth,h=canvas.clientHeight;if(!paused)angle+=Math.min(time-last,40)*.00013;last=time;ctx.clearRect(0,0,w,h);const radius=Math.min(w,h)*.47;for(let ring=0;ring<3;ring++){ctx.beginPath();for(let n=0;n<=150;n++){const t=n/150*Math.PI*2;let x=Math.cos(t)*radius,y=Math.sin(t)*radius,z=0;const tilt=.7+ring*.65;z=y*Math.sin(tilt);y*=Math.cos(tilt);const a=angle+ring*.9,xx=x*Math.cos(a)+z*Math.sin(a),zz=-x*Math.sin(a)+z*Math.cos(a),scale=700/(700+zz);const px=w/2+xx*scale,py=h/2+y*scale;if(n===0)ctx.moveTo(px,py);else ctx.lineTo(px,py)}ctx.strokeStyle=ring===1?'rgba(177,139,81,.42)':'rgba(82,117,103,.22)';ctx.lineWidth=1;ctx.stroke()}if(!paused&&visible&&!document.hidden)frame=requestAnimationFrame(draw)}function start(){if(frame)cancelAnimationFrame(frame);last=performance.now();draw(last)}motion.addEventListener('click',()=>{paused=!paused;label();start()});reduced.addEventListener('change',()=>{paused=reduced.matches;label();start()});new IntersectionObserver(entries=>{visible=entries[0].isIntersecting;start()}).observe(canvas);document.addEventListener('visibilitychange',start);const portrait=document.querySelector('[data-tilt]');portrait.addEventListener('pointermove',e=>{if(paused||e.pointerType==='touch')return;const r=portrait.getBoundingClientRect();portrait.style.transform=`rotateY(${(e.clientX-r.left-r.width/2)/r.width*9}deg) rotateX(${-(e.clientY-r.top-r.height/2)/r.height*7}deg)`});portrait.addEventListener('pointerleave',()=>portrait.style.transform='');start();
// Progressive entrance choreography: content stays visible if JS or motion is disabled.
const activeEntrances=new Set();
const entranceTargets=document.querySelectorAll('.section-title>*,.story h2,.story-copy>*,.legacy-grid article,.brand-history,.business-intro>*,.values article,.roadmap article,.benefits,.photos figure,.team-feature,.company-photos figure,.japan>*,.community-grid article,.health-mosaic figure,.partners article,.programs article,.vision h2,.contact>div');
const entranceObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{
 if(!entry.isIntersecting)return;
 const el=entry.target;entranceObserver.unobserve(el);
 if(reduced.matches||paused)return;
 const siblings=[...el.parentElement.children],index=siblings.indexOf(el);
 const delay=Math.min(index%4,3)*85;
 const photo=el.tagName==='FIGURE';
 const frames=photo?[{opacity:0,clipPath:'inset(12% 0 0 0)',transform:'translateY(35px) scale(.97)'},{opacity:1,clipPath:'inset(0% 0 0 0)',transform:'translateY(0) scale(1)'}]:[{opacity:0,transform:'translate3d(0,32px,0) rotateX(3deg)'},{opacity:1,transform:'translate3d(0,0,0) rotateX(0deg)'}];
 const animation=el.animate(frames,{duration:photo?1100:850,delay,easing:'cubic-bezier(.16,1,.3,1)',fill:'backwards'});
 activeEntrances.add(animation);animation.finished.catch(()=>{}).finally(()=>activeEntrances.delete(animation));
}),{threshold:0,rootMargin:'0px 0px -35px 0px'});
entranceTargets.forEach(el=>entranceObserver.observe(el));
function finishEntrances(){if(paused||reduced.matches){activeEntrances.forEach(a=>a.finish());portrait.style.transform=''}}
motion.addEventListener('click',finishEntrances);reduced.addEventListener('change',finishEntrances);
tabs.forEach(tab=>tab.addEventListener('click',()=>{if(paused||reduced.matches)return;document.getElementById(tab.getAttribute('aria-controls')).animate([{opacity:.15,transform:'translateY(16px)'},{opacity:1,transform:'translateY(0)'}],{duration:650,easing:'cubic-bezier(.16,1,.3,1)'})}));
if(!reduced.matches){document.querySelectorAll('.hero-copy>*,.hero-art').forEach((el,i)=>{const a=el.animate([{opacity:0,transform:'translateY(24px)'},{opacity:1,transform:'translateY(0)'}],{duration:1000,delay:Math.min(i,5)*100,easing:'cubic-bezier(.16,1,.3,1)',fill:'backwards'});activeEntrances.add(a);a.finished.catch(()=>{}).finally(()=>activeEntrances.delete(a))})}
const meter=document.createElement('div');meter.className='scroll-meter';meter.setAttribute('aria-hidden','true');document.body.append(meter);let scrollTick=false;function updateMeter(){const max=document.documentElement.scrollHeight-innerHeight;meter.style.transform=`scaleX(${max>0?Math.min(scrollY/max,1):0})`;scrollTick=false}addEventListener('scroll',()=>{if(!scrollTick){scrollTick=true;requestAnimationFrame(updateMeter)}},{passive:true});updateMeter();
